apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-search      
  namespace: zero-broker
  labels:
    app: backend-search

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend-search

  template:
    metadata:
      labels:
        app: backend-search

    spec:
      containers:
        - name: backend-search
          image: dcthefirm/backend-search:4e1e9c3e03e27e2a95724f13f8cb24a231108c5a

          ports:
            - containerPort: 4004

          envFrom:
            # - configMapRef:
            #     name: auth-configmap
            - secretRef:
                name: mongo-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 4004
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4004
            initialDelaySeconds: 15
            periodSeconds: 20