# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: auth-configmap
#   namespace: zero-broker
# data:
#   NODE_ENV: "production"
#   PORT: "5000"
#   LOG_LEVEL: "info"
#   MONGODB_DB_NAME: "zerobroker"
#   AUTH_SERVICE_URL: "http://backend-auth:5000"
#   HOME_SERVICE_URL: "http://backend-home:5000"
#   RENT_SERVICE_URL: "http://backend-rent:5000"
#   BUY_SERVICE_URL: "http://backend-buy:5000"
#   SEARCH_SERVICE_URL: "http://backend-search:5000"
#   FRONTEND_URL: "https://zerobroker.chetankesare.in"
