apiVersion: v1
kind: Service
metadata:
  name: backend-auth
  namespace: zero-broker
spec:
  selector:
    app: backend-auth
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP