apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerobroker-frontend-deployment
  namespace: zero-broker
  labels:
    app: zerobroker-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zerobroker-frontend
  template:
    metadata:
      labels:
        app: zerobroker-frontend
    spec:
      containers:
      - name: zerobroker-frontend
        image: dcthefirm/frontend:2d8483a5f93347dcedb58fa2531b967083915a9b
        ports:
        - containerPort: 80
