apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerobroker-frontend-deployment
  namespace: zero-broker
  labels:
    app: zerobroker-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zerobroker-frontend
  template:
    metadata:
      labels:
        app: zerobroker-frontend
    spec:
      containers:
      - name: zerobroker-frontend
        image: dcthefirm/frontend:4e1e9c3e03e27e2a95724f13f8cb24a231108c5a
        ports:
        - containerPort: 80
