apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerobroker-frontend-deployment
  namespace: zero-broker
  labels:
    app: zerobroker-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zerobroker-frontend
  template:
    metadata:
      labels:
        app: zerobroker-frontend
    spec:
      containers:
      - name: zerobroker-frontend
        image: dcthefirm/frontend:f6e2c5e5f8d6115115698e22d85f1514fcdbf7ba
        ports:
        - containerPort: 80
