apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrect
  namespace: zero-broker
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://dcthefirm_db_user:1DjAZjFJfezANgRH@zerobroker.4d43afc.mongodb.net/zerobroker"